import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterContext from './context/ToasterContext'
import SocketContext from './context/SocketContext'
import getCurrentUser from './actions/getCurrentUser'
import getAllUsers from './actions/getAllUsers'
import ModalContext from './context/ModalContext'
import Navbar from './components/Navbar/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  const allUsers = await getAllUsers();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalContext currentUser={currentUser}/>
        {/* <Navbar allUsers={allUsers} currentUser={currentUser}/> */}
        <ToasterContext/>
        <SocketContext currentUser={currentUser}>

          <Navbar allUsers={allUsers} currentUser={currentUser}>
            {children}
          </Navbar>
        </SocketContext>
      </body>
    </html>
  )
}
